[mosip_auth]
timestamp_format = "%Y-%m-%dT%H:%M:%S"
ida_auth_version = "1.0"
ida_auth_request_demo_id = "mosip.identity.auth"
ida_auth_request_kyc_id = "mosip.identity.kyc"
ida_auth_request_otp_id = "mosip.identity.otp"
ida_auth_env = "Staging"
authorization_header_constant = "Authorization"
partner_misp_lk = "ulFV6JECDlCKf9l3bKRXyZElq5P3G0fKC3tePHYjWOHHmMeGWL"
partner_id = "cs145-252-5"
partner_apikey = "304659"

[mosip_auth_server]
ida_auth_domain_uri = "https://api-internal.pdec.mosip.net"
ida_auth_url = "https://api-internal.pdec.mosip.net/idauthentication/v1"

[crypto_encrypt]
symmetric_key_size = 256
symmetric_nonce_size = 128
symmetric_gcm_tag_size = 128
# certificate from the below path is used to encrypt the Auth Request.
encrypt_cert_path = "credentials/pdec_ida_partner.pem"
# used to decrypt the received response
decrypt_p12_file_path = "credentials/keystore.p12"
decrypt_p12_file_password = "cs145-252-5@12345"

[crypto_signature]
algorithm = "RS256"
sign_p12_file_path = "credentials/keystore-signed.p12"
sign_p12_file_password = "cs145-252-5@12345"

[logging]
log_file_path = "authenticator.log"
log_format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
loglevel = "INFO" # can be one of "DEBUG" | "INFO" | "WARNING" | "ERROR" | "CRITICAL"
